### ISSUE TITLE
Submit package to CRAN

### ISSUE THREAD

**Issue by mwmclean** [romainfrancois/bibtex#13]

**Comment by crsh** [comment]
Are there any plans to submit the updates to CRAN soon? I'm developing a package and need to read BibTeX-files. I'd like to use `bibtex` but the available version fails to read a file if a required field is missing: 

    Error in names(out) <- keys : 
      Attribute 'names' [53] must be of same length as vector [52]

I'm considering to use `RefManageR::ReadBib`, which works fine. The only thing that's keeping me is that the package has a lot of dependencies compared to your package.

**Comment by romainfrancois** [comment]
on its way to cran.
