### ISSUE TITLE
windows and encoding

### ISSUE THREAD

**Issue by romainfrancois** [romainfrancois/bibtex#17]
@mwmclean this test fails on windows, probably some encoding issue: 

```
test_that("{Herm{\\`e}s International S.A.} and Katzfu{\\ss}, Matthias", {
  authors <- "{Herm{\\`e}s International S.A.} and Katzfu{\\ss}, Matthias"
  parsed <- bibtex:::ArrangeAuthors(authors)
  expect_match(parsed$family[[1]], "Hermès International S.A.")
  expect_match(parsed$family[[2]], "Katzfuß")
})
``` 

See for example this on r-hub. 
https://builder.r-hub.io/status/bibtex_0.4.1.tar.gz-eb660cb5067d4363a25f20980ed19e9b#L251

I'm not sure how to fix it, short of simply disabling the test ...

**Comment by mwmclean** [comment]
Strange that `RefManageR` has this exact same test and appveyor doesn't complain about it.  Makes me feel better about just skipping it on Windows.

**Comment by romainfrancois** [comment]
ok so I'll just remove the test then

**Comment by mwmclean** [comment]
Alternatively, could probably add `Encoding: UTF-8` to the DESCRIPTION file.
